from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register our viewsets
router = DefaultRouter()
router.register(r'sessions', views.AcademicSessionViewSet, basename='academicsession')
router.register(r'faculties', views.FacultyViewSet, basename='faculty')
router.register(r'departments', views.DepartmentViewSet, basename='department')
router.register(r'levels', views.LevelViewSet, basename='level')
router.register(r'courses', views.CourseViewSet, basename='course')
router.register(r'students', views.StudentViewSet, basename='student')
router.register(r'enrollments', views.CourseEnrollmentViewSet, basename='courseenrollment')
router.register(r'results', views.ResultViewSet, basename='result')
router.register(r'result-approvals', views.ResultApprovalViewSet, basename='resultapproval')

urlpatterns = [
    # Authentication endpoints
    path('auth/login/', views.login_view, name='api_login'),
    path('auth/alternative-login/', views.alternative_login_view, name='alternative-login'),
    path('auth/logout/', views.logout_view, name='api_logout'),
    path('auth/user/', views.current_user_view, name='current-user'),

    # Super Admin Professional Interface
    path('super-admin/', views.super_admin_dashboard, name='super_admin_dashboard'),
    path('super-admin/create-faculty/', views.super_admin_create_faculty, name='super_admin_create_faculty'),
    path('super-admin/create-faculty-with-dean/', views.super_admin_create_faculty_with_dean, name='super_admin_create_faculty_with_dean'),
    path('super-admin/manage-faculties/', views.super_admin_manage_faculties, name='super_admin_manage_faculties'),
    path('super-admin/faculty-details/<int:faculty_id>/', views.super_admin_faculty_details, name='super_admin_faculty_details'),
    path('super-admin/edit-faculty/<int:faculty_id>/', views.super_admin_edit_faculty, name='super_admin_edit_faculty'),
    path('super-admin/assign-dean/', views.super_admin_assign_dean, name='super_admin_assign_dean'),
    path('super-admin/faculty-reports/', views.super_admin_faculty_reports, name='super_admin_faculty_reports'),
    path('super-admin/create-department/', views.super_admin_create_department, name='super_admin_create_department'),
    path('super-admin/manage-departments/', views.super_admin_manage_departments, name='super_admin_manage_departments'),
    path('super-admin/department-details/<int:department_id>/', views.super_admin_department_details, name='super_admin_department_details'),
    path('super-admin/edit-department/<int:department_id>/', views.super_admin_edit_department, name='super_admin_edit_department'),
    path('super-admin/assign-hod/', views.super_admin_assign_hod, name='super_admin_assign_hod'),
    path('super-admin/department-reports/', views.super_admin_department_reports, name='super_admin_department_reports'),
    path('super-admin/create-user/', views.super_admin_create_user, name='super_admin_create_user'),
    path('super-admin/check-email/', views.check_email_exists, name='check_email_exists'),
    path('super-admin/check-username/', views.check_username_exists, name='check_username_exists'),
    path('super-admin/search/', views.super_admin_search, name='super_admin_search'),
    path('super-admin/delegate-permissions/<int:user_id>/', views.super_admin_delegate_permissions, name='super_admin_delegate_permissions'),
    path('super-admin/permission-delegations/', views.super_admin_permission_delegations, name='super_admin_permission_delegations'),
    path('super-admin/create-delegation/', views.super_admin_create_delegation, name='super_admin_create_delegation'),
    path('super-admin/delegation-history/', views.super_admin_delegation_history, name='super_admin_delegation_history'),
    path('super-admin/export-delegation-report/', views.super_admin_export_delegation_report, name='super_admin_export_delegation_report'),
    path('super-admin/revoke-delegation/<int:delegation_id>/', views.super_admin_revoke_delegation, name='super_admin_revoke_delegation'),
    path('super-admin/get-role-holders/', views.get_role_holders, name='get_role_holders'),
    path('super-admin/get-eligible-delegates/', views.get_eligible_delegates, name='get_eligible_delegates'),
    path('super-admin/check-delegation-conflicts/', views.check_delegation_conflicts_view, name='check_delegation_conflicts'),
    path('super-admin/manage-users/', views.super_admin_manage_users, name='super_admin_manage_users'),
    path('super-admin/debug-users/', views.debug_user_display, name='debug_user_display'),
    path('super-admin/get-all-role-holders/', views.super_admin_get_all_role_holders, name='get_all_role_holders'),
    path('super-admin/get-departments/', views.get_departments, name='get_departments'),
    path('super-admin/delegate-permission/', views.super_admin_delegate_permission, name='super_admin_delegate_permission'),
    path('super-admin/user-details/<int:user_id>/', views.super_admin_user_details, name='super_admin_user_details'),
    path('super-admin/edit-user/<int:user_id>/', views.super_admin_edit_user, name='super_admin_edit_user'),
    path('super-admin/change-password/<int:user_id>/', views.super_admin_change_password, name='super_admin_change_password'),
    path('super-admin/assign-roles/', views.super_admin_assign_roles, name='super_admin_assign_roles'),
    path('super-admin/user-reports/', views.super_admin_user_reports, name='super_admin_user_reports'),
    path('super-admin/role-overview/', views.super_admin_role_overview, name='super_admin_role_overview'),
    path('super-admin/bulk-assign/', views.super_admin_bulk_assign, name='super_admin_bulk_assign'),
    path('super-admin/audit-log/', views.super_admin_audit_log, name='super_admin_audit_log'),
    path('super-admin/faculty/<int:faculty_id>/details/', views.super_admin_faculty_details, name='super_admin_faculty_details'),
    path('super-admin/faculty/<int:faculty_id>/assign-dean/', views.super_admin_assign_dean_single, name='super_admin_assign_dean_single'),
    path('super-admin/system-settings/', views.super_admin_system_settings, name='super_admin_system_settings'),

    # Super Admin Session Management URLs
    path('super-admin/create-session/', views.super_admin_create_session, name='super_admin_create_session'),
    path('super-admin/manage-sessions/', views.super_admin_manage_sessions, name='super_admin_manage_sessions'),
    path('super-admin/activate-session/', views.super_admin_activate_session, name='super_admin_activate_session'),
    path('super-admin/deactivate-session/<int:session_id>/', views.super_admin_deactivate_session, name='super_admin_deactivate_session'),
    path('super-admin/lock-session/<int:session_id>/', views.super_admin_lock_session, name='super_admin_lock_session'),
    path('super-admin/unlock-session/<int:session_id>/', views.super_admin_unlock_session, name='super_admin_unlock_session'),
    path('super-admin/delete-session/<int:session_id>/', views.super_admin_delete_session, name='super_admin_delete_session'),

    # Faculty Dean URLs
    path('faculty-dean/', views.faculty_dean_dashboard, name='faculty_dean_dashboard'),
    path('faculty-dean/departments/', views.faculty_dean_departments, name='faculty_dean_departments'),
    path('faculty-dean/students/', views.faculty_dean_students, name='faculty_dean_students'),
    path('faculty-dean/lecturers/', views.faculty_dean_lecturers, name='faculty_dean_lecturers'),
    path('faculty-dean/lecturers/create/', views.faculty_dean_create_lecturer, name='faculty_dean_create_lecturer'),
    path('faculty-dean/courses/', views.faculty_dean_courses, name='faculty_dean_courses'),
    path('faculty-dean/results/', views.faculty_dean_results, name='faculty_dean_results'),
    path('faculty-dean/pending-results/', views.faculty_dean_pending_results, name='faculty_dean_pending_results'),
    path('faculty-dean/reports/', views.faculty_dean_reports, name='faculty_dean_reports'),
    path('faculty-dean/statistics/', views.faculty_dean_statistics, name='faculty_dean_statistics'),
    path('faculty-dean/settings/', views.faculty_dean_settings, name='faculty_dean_settings'),
    path('faculty-dean/create-department/', views.faculty_dean_create_department, name='faculty_dean_create_department'),
    path('faculty-dean/assign-hod/<int:department_id>/', views.faculty_dean_assign_hod, name='faculty_dean_assign_hod'),
    path('faculty-dean/course-assignments/', views.faculty_dean_course_assignments, name='faculty_dean_course_assignments'),
    path('faculty-dean/assign-course/', views.faculty_dean_assign_course, name='faculty_dean_assign_course'),
    path('faculty-dean/unassign-course/<int:assignment_id>/', views.faculty_dean_unassign_course, name='faculty_dean_unassign_course'),
    path('faculty-dean/grading-thresholds/', views.faculty_dean_grading_thresholds, name='faculty_dean_grading_thresholds'),
    path('faculty-dean/carryover-students/', views.faculty_dean_carryover_students, name='faculty_dean_carryover_students'),

    # Delete functionality for testing
    path('super-admin/delete-user/<int:user_id>/', views.super_admin_delete_user, name='super_admin_delete_user'),
    path('super-admin/delete-role/<int:role_id>/', views.super_admin_delete_role, name='super_admin_delete_role'),
    path('super-admin/add-role/', views.super_admin_add_role, name='super_admin_add_role'),
    path('super-admin/delete-faculty/<int:faculty_id>/', views.super_admin_delete_faculty, name='super_admin_delete_faculty'),

    # User role management (Super Admin only)
    path('users/', views.list_users, name='list-users'),
    path('users/<int:user_id>/roles/', views.assign_role, name='assign-role'),
    path('users/<int:user_id>/roles/<int:role_id>/', views.remove_role, name='remove-role'),
    path('users/<int:user_id>/alternative-login/', views.create_alternative_login, name='create-alternative-login'),

    path('external/authenticate/', views.external_authenticate, name='external-authenticate'),
    path('external/validate/', views.validate_token, name='validate-token'),
    path('external/revoke/', views.revoke_token, name='revoke-token'),
    path('external/docs/', views.api_documentation, name='api-documentation'),

    # Web Interface URLs (iOS Aesthetic)
    path('login/', views.web_login_view, name='web_login'),
    path('logout/', views.web_logout_view, name='web_logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('students/', views.students_view, name='students'),
    path('courses/', views.courses_view, name='courses'),
    path('results/', views.results_view, name='results'),

    # Placeholder URLs for dashboard links
    path('manage/users/', views.manage_users_view, name='manage_users'),
    path('manage/faculties/', views.manage_faculties_view, name='manage_faculties'),
    path('manage/departments/', views.manage_departments_view, name='manage_departments'),
    path('manage/sessions/', views.manage_sessions_view, name='manage_sessions'),
    path('settings/', views.system_settings_view, name='system_settings'),
    path('results/approve/', views.approve_results_view, name='approve_results'),
    path('results/publish/', views.publish_results_view, name='publish_results'),
    path('contact-admin/', views.contact_admin_view, name='contact_admin'),

    # Faculty Dean Professional Interface
    path('faculty-dean/', views.faculty_dean_dashboard, name='faculty_dean_dashboard'),
    path('faculty-dean/departments/', views.faculty_dean_departments, name='faculty_dean_departments'),
    path('faculty-dean/departments/create/', views.faculty_dean_create_department, name='faculty_dean_create_department'),
    path('faculty-dean/hods/', views.faculty_dean_hods, name='faculty_dean_hods'),
    path('faculty-dean/hods/create/', views.faculty_dean_create_hod, name='faculty_dean_create_hod'),
    path('faculty-dean/grading-system/', views.faculty_dean_grading_system, name='faculty_dean_grading_system'),
    path('faculty-dean/course-offerings/', views.faculty_dean_course_offerings, name='faculty_dean_course_offerings'),
    path('faculty-dean/results/pending/', views.faculty_dean_pending_results, name='faculty_dean_pending_results'),
    path('faculty-dean/results/history/', views.faculty_dean_result_history, name='faculty_dean_result_history'),
    path('faculty-dean/results/bulk-approve/', views.faculty_dean_bulk_approve, name='faculty_dean_bulk_approve'),
    path('faculty-dean/reports/', views.faculty_dean_reports, name='faculty_dean_reports'),
    path('faculty-dean/courses/', views.faculty_dean_courses, name='faculty_dean_courses'),
    path('faculty-dean/lecturers/', views.faculty_dean_lecturers, name='faculty_dean_lecturers'),
    path('faculty-dean/results/all/', views.faculty_dean_all_results, name='faculty_dean_all_results'),
    path('faculty-dean/results/search/', views.faculty_dean_result_search, name='faculty_dean_result_search'),
    path('faculty-dean/statistics/', views.faculty_dean_statistics, name='faculty_dean_statistics'),
    path('faculty-dean/pass-rates/', views.faculty_dean_pass_rates, name='faculty_dean_pass_rates'),
    path('faculty-dean/export/', views.faculty_dean_export, name='faculty_dean_export'),
    path('faculty-dean/results/<int:result_id>/approve/', views.faculty_dean_approve_result, name='faculty_dean_approve_result'),
    path('faculty-dean/results/<int:result_id>/view/', views.faculty_dean_view_result, name='faculty_dean_view_result'),

    # Additional Faculty Dean URLs
    path('faculty-dean/grading/create/', views.faculty_dean_create_grading_scale, name='faculty_dean_create_grading_scale'),
    path('faculty-dean/grading/edit/', views.faculty_dean_edit_grading_scale, name='faculty_dean_edit_grading_scale'),
    path('faculty-dean/grading/add-range/', views.faculty_dean_add_grade_range, name='faculty_dean_add_grade_range'),
    path('faculty-dean/grading/edit-range/<int:range_id>/', views.faculty_dean_edit_grade_range, name='faculty_dean_edit_grade_range'),
    path('faculty-dean/carryover/create/', views.faculty_dean_create_carryover_criteria, name='faculty_dean_create_carryover_criteria'),
    path('faculty-dean/carryover/edit/', views.faculty_dean_edit_carryover_criteria, name='faculty_dean_edit_carryover_criteria'),
    path('faculty-dean/grading/template/<str:template_type>/', views.faculty_dean_apply_template, name='faculty_dean_apply_template'),

    # Additional Faculty Dean URLs for new workflow
    path('faculty-dean/department/<int:department_id>/details/', views.faculty_dean_department_details, name='faculty_dean_department_details'),
    path('faculty-dean/department/<int:department_id>/assign-hod/', views.faculty_dean_assign_hod_single, name='faculty_dean_assign_hod_single'),
    path('faculty-dean/department/<int:department_id>/change-hod/', views.faculty_dean_change_hod, name='faculty_dean_change_hod'),
    path('faculty-dean/department/<int:department_id>/edit/', views.faculty_dean_edit_department, name='faculty_dean_edit_department'),
    path('faculty-dean/departments/bulk-import/', views.faculty_dean_bulk_import_departments, name='faculty_dean_bulk_import_departments'),
    path('faculty-dean/departments/reports/', views.faculty_dean_department_reports, name='faculty_dean_department_reports'),
    path('faculty-dean/departments/export/', views.faculty_dean_export_departments, name='faculty_dean_export_departments'),

    # Faculty Dean Student Management
    path('faculty-dean/create-student/', views.faculty_dean_create_student, name='faculty_dean_create_student'),
    path('faculty-dean/bulk-create-students/', views.faculty_dean_bulk_create_students, name='faculty_dean_bulk_create_students'),
    path('faculty-dean/api/student/<int:student_id>/edit/', views.faculty_dean_edit_student, name='faculty_dean_edit_student'),
    path('faculty-dean/api/student/<int:student_id>/delete/', views.faculty_dean_delete_student, name='faculty_dean_delete_student'),
    path('faculty-dean/api/student/<int:student_id>/results/', views.faculty_dean_student_results, name='faculty_dean_student_results'),
    path('faculty-dean/api/student/<int:student_id>/reset-password/', views.faculty_dean_reset_password, name='faculty_dean_reset_password'),
    path('faculty-dean/api/progress-students/', views.faculty_dean_progress_students, name='faculty_dean_progress_students'),

    # Lecturer Professional Interface
    path('lecturer/', views.lecturer_dashboard, name='lecturer_dashboard'),
    path('lecturer/enroll-students/', views.lecturer_enroll_students, name='lecturer_enroll_students'),
    path('lecturer/bulk-enroll/', views.lecturer_bulk_enroll, name='lecturer_bulk_enroll'),
    path('lecturer/manage-enrollments/', views.lecturer_manage_enrollments, name='lecturer_manage_enrollments'),
    path('lecturer/student-list/', views.lecturer_student_list, name='lecturer_student_list'),
    path('lecturer/courses/', views.lecturer_courses, name='lecturer_courses'),
    path('lecturer/course-details/', views.lecturer_course_details, name='lecturer_course_details'),
    path('lecturer/enter-results/', views.lecturer_enter_results, name='lecturer_enter_results'),
    path('lecturer/download-csv-template/', views.lecturer_download_csv_template, name='lecturer_download_csv_template'),
    path('lecturer/upload-csv-results/', views.lecturer_upload_csv_results, name='lecturer_upload_csv_results'),
    path('lecturer/bulk-results/', views.lecturer_bulk_results, name='lecturer_bulk_results'),
    path('lecturer/draft-results/', views.lecturer_draft_results, name='lecturer_draft_results'),
    path('lecturer/edit-results/', views.lecturer_edit_results, name='lecturer_edit_results'),
    path('lecturer/submit-results/', views.lecturer_submit_results, name='lecturer_submit_results'),
    path('lecturer/result-status/', views.lecturer_result_status, name='lecturer_result_status'),
    path('lecturer/corrections/', views.lecturer_corrections, name='lecturer_corrections'),
    path('lecturer/resubmit/', views.lecturer_resubmit, name='lecturer_resubmit'),
    path('lecturer/course/<int:course_id>/students/', views.lecturer_course_students, name='lecturer_course_students'),
    path('lecturer/course/<int:course_id>/results/', views.lecturer_course_results, name='lecturer_course_results'),
    path('lecturer/student/<int:student_id>/details/', views.lecturer_student_details, name='lecturer_student_details'),
    path('lecturer/enrollment/<int:enrollment_id>/unenroll/', views.lecturer_unenroll_student, name='lecturer_unenroll_student'),
    path('lecturer/course-thresholds/', views.lecturer_course_thresholds, name='lecturer_course_thresholds'),

    # Exam Officer Professional Interface
    path('exam-officer/', views.exam_officer_dashboard, name='exam_officer_dashboard'),
    path('exam-officer/pending-results/', views.exam_officer_pending_results, name='exam_officer_pending_results'),
    path('exam-officer/export-csv/', views.exam_officer_export_csv, name='exam_officer_export_csv'),
    path('exam-officer/validate-results/', views.exam_officer_validate_results, name='exam_officer_validate_results'),
    path('exam-officer/approve-results/', views.exam_officer_approve_results, name='exam_officer_approve_results'),
    path('exam-officer/reject-results/', views.exam_officer_reject_results, name='exam_officer_reject_results'),
    path('exam-officer/submit-to-hod/', views.exam_officer_submit_to_hod, name='exam_officer_submit_to_hod'),
    path('exam-officer/result-history/', views.exam_officer_result_history, name='exam_officer_result_history'),
    path('exam-officer/add-students/', views.exam_officer_add_students, name='exam_officer_add_students'),
    path('exam-officer/bulk-students/', views.exam_officer_bulk_students, name='exam_officer_bulk_students'),
    path('exam-officer/student-list/', views.exam_officer_student_list, name='exam_officer_student_list'),
    path('exam-officer/student-records/', views.exam_officer_student_records, name='exam_officer_student_records'),
    path('exam-officer/carryovers/', views.exam_officer_carryovers, name='exam_officer_carryovers'),
    path('exam-officer/carryover-students/', views.exam_officer_carryover_students, name='exam_officer_carryover_students'),
    path('exam-officer/carryover-export/', views.exam_officer_carryover_export, name='exam_officer_carryover_export'),
    path('exam-officer/export/students/', views.exam_officer_export_students, name='exam_officer_export_students'),
    path('exam-officer/export/gpa/', views.exam_officer_export_gpa, name='exam_officer_export_gpa'),
    path('exam-officer/export/results/', views.exam_officer_export_results, name='exam_officer_export_results'),
    path('exam-officer/export/approved/', views.exam_officer_export_approved, name='exam_officer_export_approved'),
    path('exam-officer/export/carryovers/', views.exam_officer_export_carryovers, name='exam_officer_export_carryovers'),
    path('exam-officer/export/carryover-students/', views.exam_officer_export_carryover_students, name='exam_officer_export_carryover_students'),
    path('exam-officer/result/<int:result_id>/review/', views.exam_officer_review_result, name='exam_officer_review_result'),
    path('exam-officer/result/<int:result_id>/approve/', views.exam_officer_approve_single, name='exam_officer_approve_single'),

    # DAAA Professional Interface
    path('daaa/', views.daaa_dashboard, name='daaa_dashboard'),
    path('daaa/create-session/', views.daaa_create_session, name='daaa_create_session'),
    path('daaa/manage-sessions/', views.daaa_manage_sessions, name='daaa_manage_sessions'),
    path('daaa/activate-session/', views.daaa_activate_session, name='daaa_activate_session'),
    path('daaa/deactivate-session/<int:session_id>/', views.daaa_deactivate_session, name='daaa_deactivate_session'),
    path('daaa/lock-session/<int:session_id>/', views.daaa_lock_session, name='daaa_lock_session'),
    path('daaa/unlock-session/<int:session_id>/', views.daaa_unlock_session, name='daaa_unlock_session'),
    path('daaa/delete-session/<int:session_id>/', views.daaa_delete_session, name='daaa_delete_session'),
    path('daaa/pending-results/', views.daaa_pending_results, name='daaa_pending_results'),
    path('daaa/result-history/', views.daaa_result_history, name='daaa_result_history'),
    path('daaa/review-results/', views.daaa_review_results, name='daaa_review_results'),
    path('daaa/approve-results/', views.daaa_approve_results, name='daaa_approve_results'),
    path('daaa/reject-results/', views.daaa_reject_results, name='daaa_reject_results'),
    path('daaa/submit-to-senate/', views.daaa_submit_to_senate, name='daaa_submit_to_senate'),
    path('daaa/senate-reports/', views.daaa_senate_reports, name='daaa_senate_reports'),
    path('daaa/publish-results/', views.daaa_publish_results, name='daaa_publish_results'),
    path('daaa/publication-settings/', views.daaa_publication_settings, name='daaa_publication_settings'),
    path('daaa/published-sessions/', views.daaa_published_sessions, name='daaa_published_sessions'),
    path('daaa/notification-log/', views.daaa_notification_log, name='daaa_notification_log'),
    path('daaa/send-notifications/', views.daaa_send_notifications, name='daaa_send_notifications'),
    path('daaa/email-status/', views.daaa_email_status, name='daaa_email_status'),

    # Additional DAAA Notification URLs
    path('daaa/bulk-email/', views.daaa_bulk_email, name='daaa_bulk_email'),
    path('daaa/notification-templates/', views.daaa_notification_templates, name='daaa_notification_templates'),
    path('daaa/email-settings/', views.daaa_email_settings, name='daaa_email_settings'),
    path('daaa/send-notification/', views.daaa_send_notification, name='daaa_send_notification'),
    path('daaa/notification/<int:notification_id>/details/', views.daaa_notification_details, name='daaa_notification_details'),
    path('daaa/notification/<int:notification_id>/resend-email/', views.daaa_resend_email, name='daaa_resend_email'),
    path('daaa/email-logs/', views.daaa_email_logs, name='daaa_email_logs'),
    path('daaa/test-email/', views.daaa_test_email, name='daaa_test_email'),

    # Additional DAAA Reporting URLs
    path('daaa/reports/', views.daaa_faculty_summary, name='daaa_reports'),
    path('daaa/reports/student-performance/', views.daaa_student_performance_report, name='daaa_student_performance_report'),
    path('daaa/reports/gpa-analysis/', views.daaa_gpa_analysis, name='daaa_gpa_analysis'),
    path('daaa/reports/graduation/', views.daaa_graduation_report, name='daaa_graduation_report'),
    path('daaa/reports/academic-standing/', views.daaa_academic_standing, name='daaa_academic_standing'),
    path('daaa/reports/course-performance/', views.daaa_course_performance, name='daaa_course_performance'),
    path('daaa/reports/pass-rate/', views.daaa_pass_rate_analysis, name='daaa_pass_rate_analysis'),
    path('daaa/reports/department-analysis/', views.daaa_department_analysis, name='daaa_department_analysis'),
    path('daaa/reports/enrollment-trends/', views.daaa_enrollment_trends, name='daaa_enrollment_trends'),
    path('daaa/reports/capacity-analysis/', views.daaa_capacity_analysis, name='daaa_capacity_analysis'),
    path('daaa/reports/session-summary/', views.daaa_session_summary, name='daaa_session_summary'),
    path('daaa/reports/workflow-analysis/', views.daaa_workflow_analysis, name='daaa_workflow_analysis'),
    path('daaa/reports/custom/', views.daaa_custom_report, name='daaa_custom_report'),
    path('daaa/reports/history/', views.daaa_report_history, name='daaa_report_history'),
    path('daaa/reports/<int:report_id>/download/', views.daaa_download_report, name='daaa_download_report'),
    path('daaa/reports/<int:report_id>/regenerate/', views.daaa_regenerate_report, name='daaa_regenerate_report'),
    path('daaa/analytics/detailed/', views.daaa_detailed_analytics, name='daaa_detailed_analytics'),
    path('daaa/analytics/trends/', views.daaa_trend_analysis, name='daaa_trend_analysis'),
    path('daaa/analytics/comparative/', views.daaa_comparative_analysis, name='daaa_comparative_analysis'),
    path('daaa/faculty-summary/', views.daaa_faculty_summary, name='daaa_faculty_summary'),
    path('daaa/faculty-comparison/', views.daaa_faculty_comparison, name='daaa_faculty_comparison'),
    path('daaa/export-university/', views.daaa_export_university, name='daaa_export_university'),
    path('daaa/export-senate/', views.daaa_export_senate, name='daaa_export_senate'),
    path('daaa/audit-log/', views.daaa_audit_log, name='daaa_audit_log'),
    path('daaa/system-health/', views.daaa_system_health, name='daaa_system_health'),
    path('daaa/faculty/<int:faculty_id>/details/', views.daaa_faculty_details, name='daaa_faculty_details'),
    path('daaa/result/<int:result_id>/review/', views.daaa_review_single_result, name='daaa_review_single_result'),
    path('daaa/result/<int:result_id>/approve/', views.daaa_approve_single_result, name='daaa_approve_single_result'),

    # Additional DAAA URLs
    path('daaa/session/<int:session_id>/edit/', views.daaa_edit_session, name='daaa_edit_session'),
    path('daaa/session/<int:session_id>/details/', views.daaa_session_details, name='daaa_session_details'),
    path('daaa/session/<int:session_id>/activate/', views.daaa_activate_session_single, name='daaa_activate_session_single'),
    path('daaa/sessions/archive/', views.daaa_archive_sessions, name='daaa_archive_sessions'),
    path('daaa/sessions/reports/', views.daaa_session_reports, name='daaa_session_reports'),

    # Senate Professional Interface
    path('senate/', views.senate_dashboard, name='senate_dashboard'),
    path('senate/pending-results/', views.senate_pending_results, name='senate_pending_results'),
    path('senate/review-results/', views.senate_review_results, name='senate_review_results'),
    path('senate/approve-results/', views.senate_approve_results, name='senate_approve_results'),
    path('senate/send-back/', views.senate_send_back, name='senate_send_back'),
    path('senate/seal-results/', views.senate_seal_results, name='senate_seal_results'),
    path('senate/final-archive/', views.senate_final_archive, name='senate_final_archive'),
    path('senate/session-overview/', views.senate_session_overview, name='senate_session_overview'),
    path('senate/session-reports/', views.senate_session_reports, name='senate_session_reports'),
    path('senate/faculty-summary/', views.senate_faculty_summary, name='senate_faculty_summary'),
    path('senate/university-report/', views.senate_university_report, name='senate_university_report'),
    path('senate/faculty/<int:faculty_id>/details/', views.senate_faculty_details, name='senate_faculty_details'),
    path('senate/result/<int:result_id>/review/', views.senate_review_single_result, name='senate_review_single_result'),
    path('senate/result/<int:result_id>/approve/', views.senate_approve_single_result, name='senate_approve_single_result'),
    path('senate/approval-history/', views.senate_approval_history, name='senate_approval_history'),

    # Student Professional Interface
    path('student/', views.student_dashboard, name='student_dashboard'),
    path('student/current-results/', views.student_current_results, name='student_current_results'),
    path('student/all-results/', views.student_all_results, name='student_all_results'),
    path('student/result-history/', views.student_result_history, name='student_result_history'),
    path('student/transcript/', views.student_transcript, name='student_transcript'),
    path('student/download-result/', views.student_download_result, name='student_download_result'),
    path('student/download-transcript/', views.student_download_transcript, name='student_download_transcript'),
    path('student/submit-complaint/', views.student_submit_complaint, name='student_submit_complaint'),
    path('student/my-complaints/', views.student_my_complaints, name='student_my_complaints'),
    path('student/help/', views.student_help, name='student_help'),
    path('student/contact/', views.student_contact, name='student_contact'),
    path('student/result/<int:result_id>/details/', views.student_result_details, name='student_result_details'),

    # Admission Officer Professional Interface
    path('admission/', views.admission_officer_dashboard, name='admission_officer_dashboard'),
    path('admission/register-student/', views.admission_register_student, name='admission_register_student'),
    path('admission/quick-register/', views.admission_quick_register, name='admission_quick_register'),
    path('admission/edit-student/', views.admission_edit_student, name='admission_edit_student'),
    path('admission/verify-student/', views.admission_verify_student, name='admission_verify_student'),
    path('admission/bulk-register/', views.admission_bulk_register, name='admission_bulk_register'),
    path('admission/import-excel/', views.admission_import_excel, name='admission_import_excel'),
    path('admission/download-template/', views.admission_download_template, name='admission_download_template'),
    path('admission/bulk-update/', views.admission_bulk_update, name='admission_bulk_update'),
    path('admission/search-students/', views.admission_search_students, name='admission_search_students'),
    path('admission/filter-by-faculty/', views.admission_filter_by_faculty, name='admission_filter_by_faculty'),
    path('admission/filter-by-level/', views.admission_filter_by_level, name='admission_filter_by_level'),
    path('admission/filter-by-session/', views.admission_filter_by_session, name='admission_filter_by_session'),
    path('admission/update-placement/', views.admission_update_placement, name='admission_update_placement'),
    path('admission/level-promotion/', views.admission_level_promotion, name='admission_level_promotion'),
    path('admission/transfer-student/', views.admission_transfer_student, name='admission_transfer_student'),
    path('admission/placement-reports/', views.admission_placement_reports, name='admission_placement_reports'),
    path('admission/all-students/', views.admission_all_students, name='admission_all_students'),
    path('admission/student/<int:student_id>/details/', views.admission_student_details, name='admission_student_details'),
    path('admission/student/<int:student_id>/edit/', views.admission_edit_student_single, name='admission_edit_student_single'),
    path('admission/registration-report/', views.admission_registration_report, name='admission_registration_report'),
    path('admission/export-students/', views.admission_export_students, name='admission_export_students'),
    path('admission/faculty-summary/', views.admission_faculty_summary, name='admission_faculty_summary'),
    path('admission/faculty/<int:faculty_id>/students/', views.admission_faculty_students, name='admission_faculty_students'),
    path('admission/faculty/<int:faculty_id>/register/', views.admission_faculty_register, name='admission_faculty_register'),

    # HOD Professional Interface
    path('hod/', views.hod_dashboard, name='hod_dashboard'),
    path('hod/create-course/', views.hod_create_course, name='hod_create_course'),
    path('hod/manage-courses/', views.hod_manage_courses, name='hod_manage_courses'),
    path('hod/course-assignments/', views.hod_course_assignments, name='hod_course_assignments'),
    path('hod/course-reports/', views.hod_course_reports, name='hod_course_reports'),
    path('hod/assign-lecturers/', views.hod_assign_lecturers, name='hod_assign_lecturers'),
    path('hod/lecturer-performance/', views.hod_lecturer_performance, name='hod_lecturer_performance'),
    path('hod/lecturer-list/', views.hod_lecturer_list, name='hod_lecturer_list'),
    path('hod/workload-analysis/', views.hod_workload_analysis, name='hod_workload_analysis'),
    path('hod/pending-results/', views.hod_pending_results, name='hod_pending_results'),
    path('hod/review-results/', views.hod_review_results, name='hod_review_results'),
    path('hod/approve-results/', views.hod_approve_results, name='hod_approve_results'),
    path('hod/reject-results/', views.hod_reject_results, name='hod_reject_results'),
    path('hod/submit-to-dean/', views.hod_submit_to_dean, name='hod_submit_to_dean'),
    path('hod/result-status/', views.hod_result_status, name='hod_result_status'),

    # HOD Course Management API endpoints
    path('hod/api/lecturers/', views.hod_get_lecturers, name='hod_get_lecturers'),
    path('hod/api/course/<int:course_id>/assign/', views.hod_assign_course_lecturer, name='hod_assign_course_lecturer'),
    path('hod/api/course/<int:course_id>/edit/', views.hod_edit_course, name='hod_edit_course'),
    path('hod/api/course/<int:course_id>/delete/', views.hod_delete_course, name='hod_delete_course'),

    # Consolidated Navigation URLs (Smart Multi-Role Access)
    path('consolidated/students/', views.consolidated_students_view, name='consolidated_students'),
    path('consolidated/lecturers/', views.consolidated_lecturers_view, name='consolidated_lecturers'),
    path('consolidated/courses/', views.consolidated_courses_view, name='consolidated_courses'),
    path('consolidated/results/', views.consolidated_results_view, name='consolidated_results'),
    path('consolidated/reports/', views.consolidated_reports_view, name='consolidated_reports'),
    path('hod/department-summary/', views.hod_department_summary, name='hod_department_summary'),
    path('hod/export-results/', views.hod_export_results, name='hod_export_results'),
    path('hod/result/<int:result_id>/review/', views.hod_review_single_result, name='hod_review_single_result'),
    path('hod/result/<int:result_id>/approve/', views.hod_approve_single_result, name='hod_approve_single_result'),

    # Include router URLs
    path('', include(router.urls)),
]
