# Generated by Django 5.2.4 on 2025-07-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_email_sent_notification_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('ROLE_ASSIGN', 'Role Assignment'), ('CREATE_FACULTY', 'Create Faculty'), ('CREATE_FACULTY_WITH_DEAN', 'Create Faculty with Dean'), ('ASSIGN_DEAN', 'Assign Faculty Dean'), ('CREATE_USER', 'Create User')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
