# Generated by Django 5.2.4 on 2025-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog_department_auditlog_faculty_auditlog_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
