# Generated by Django 5.2.4 on 2025-07-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_faculty_description'),
    ]

    operations = [
    ]
