# Generated by Django 5.2.4 on 2025-07-26 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_permissiondelegation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissiondelegation',
            unique_together={('delegate', 'delegated_role', 'status')},
        ),
        migrations.AddField(
            model_name='permissiondelegation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.permissiondelegation'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissiondelegation',
            name='delegated_role',
            field=models.ForeignKey(help_text='The specific role being temporarily delegated', on_delete=django.db.models.deletion.CASCADE, to='accounts.userrole'),
        ),
        migrations.AlterField(
            model_name='permissiondelegation',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='permissiondelegation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10),
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='revocation_reason',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='revoked_at',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='start_date',
        ),
    ]
