# Generated by Django 5.2.4 on 2025-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fix_auditlog_user_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiondelegation',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When the delegation expires (optional)', null=True),
        ),
        migrations.AddField(
            model_name='permissiondelegation',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When the delegation becomes active (optional)', null=True),
        ),
    ]
