# Generated by Django 5.2.5 on 2025-07-25 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_delegation_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_students', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_students', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LevelProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression_type', models.CharField(choices=[('AUTOMATIC', 'Automatic Progression'), ('MANUAL', 'Manual Progression'), ('REPEAT', 'Repeat Level'), ('TRANSFER', 'Transfer Student')], default='AUTOMATIC', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_from', to='accounts.level')),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_from', to='accounts.academicsession')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progressions', to='accounts.student')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_to', to='accounts.level')),
                ('to_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_to', to='accounts.academicsession')),
            ],
            options={
                'ordering': ['-processed_at'],
                'unique_together': {('student', 'from_session', 'to_session')},
            },
        ),
    ]
