# Generated by Django 5.2.5 on 2025-07-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_optimize_student_search'),
        ('accounts', '0013_student_current_session_student_graduation_session_and_more'),
    ]

    operations = [
    ]
