# Generated by Django 5.2.5 on 2025-07-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20250725_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_max_score', models.DecimalField(decimal_places=2, default=30.0, help_text='Maximum CA score (default: 30)', max_digits=5)),
                ('exam_max_score', models.DecimalField(decimal_places=2, default=70.0, help_text='Maximum Exam score (default: 70)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='accounts.courseassignment')),
            ],
            options={
                'verbose_name': 'Course Threshold',
                'verbose_name_plural': 'Course Thresholds',
            },
        ),
    ]
