# Generated by Django 5.2.5 on 2025-07-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_comprehensive_grading_system'),
        ('accounts', '0017_add_result_rejection_fields'),
    ]

    operations = [
    ]
