# Generated by Django 5.2.5 on 2025-07-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_carryoverstudent_gradingthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingthreshold',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Grade points for GPA calculation', max_digits=3),
        ),
    ]
