# Generated by Django 5.2.5 on 2025-08-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20250731_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='modification_reason',
            field=models.TextField(blank=True, help_text='Reason for the modification'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_ca_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_carryover_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_grade',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='original_ca_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='original_carryover_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='original_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='original_grade',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='original_total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.result'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('ROLE_ASSIGN', 'Role Assignment'), ('CREATE_FACULTY', 'Create Faculty'), ('CREATE_FACULTY_WITH_DEAN', 'Create Faculty with Dean'), ('ASSIGN_DEAN', 'Assign Faculty Dean'), ('CREATE_USER', 'Create User'), ('MODIFY_RESULT', 'Modify Result'), ('CARRYOVER_STATUS_CHANGE', 'Carryover Status Change'), ('APPROVE_RESULT', 'Approve Result'), ('REJECT_RESULT', 'Reject Result'), ('FORWARD_RESULT', 'Forward Result')], max_length=30),
        ),
    ]
