# Generated by Django 5.2.5 on 2025-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_enhance_audit_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultapprovalhistory',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded'), ('SCORE_EDITED', 'Score Edited'), ('AUTO_PROGRESSED', 'Auto Progressed')], max_length=20),
        ),
    ]
